SIZE = [1, 60, 60, 24, 30, 12]
UNITS = ['seconds', 'minutes', 'hours', 'days', 'months', 'years']
START = 'Start date:'
END = 'End date:'
SUCCESS = 'Macro finished successfully!'
START_REGEX = r'Start date: \w{2} \w{3} \d{1,2} \d{1,2}:\d{1,2}:\d{1,2} \w+ \d{4}'
END_REGEX = r'End date: \w{2} \w{3} \d{1,2} \d{1,2}:\d{1,2}:\d{1,2} \w+ \d{4}'
MONTH_ARR = ['янв', 'фев', 'мар', 'апр', 'май', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек']
# UNSUCCESSFUL_OUT = 'unsuccessful.txt'
RUN_REGEX = r'run\d+'
RUN_EXTENSION = '.root'
# DB_USER = "db_reader"
# DB_PASS = "reader_pass"
# DB_NAME = "bmn_db"
# DB_HOST = "vm221-53.jinr.ru"
DPI = 300
FOLDERS_IGNORE = ['__pycache__', 'myenv']
BINS = 10
BINS_PER_EVENT = 10